---
# Define the name and description of the OpenShift project
- set_fact: project="dev"
- set_fact: project_description="Development Environment for Microservices Scrum"
- set_fact: expose_basic_ui=false
    
- include: environment-setup.yml

- name: Create the microservices applications using the source to image builder
  include_tasks: "{{ workdir }}/{{ item.repo }}//create-app-tasks.yml repo={{ item.repo }}"
  with_items: "{{ microservices_scrum_projects }}"
  tags:
    - openshift   

- name: Allows jenkins to access the dev environment
  shell: "oc policy add-role-to-user edit system:serviceaccount:cicd:jenkins -n dev"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - jenkins   
