---
- name: Install Estafet Microservices Application in Openshift
  hosts: local
  vars_files: 
    - vars/microservices-vars.yml
    - vars/libraries-vars.yml    
  tasks:          
    - include_role:
        name: local-environment-setup    
      vars:
        product: ms-scrum
        product_description: Microservices Scrum Demo
        test: false
        repo: estafet-microservices-scrum
        workdir: ~/.estafet
