---
- include: "{{ inventory_dir }}/variables/users-vars.yml"

- name: Allow users to access project
  shell: 'oc policy add-role-to-user edit {{ item }} -n {{ project }}'
  when: item != 'admin'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift

    