---
# Define the name and description of the OpenShift project
- set_fact: project="prod"
- set_fact: project_description="Production/Demo Environment for Microservices Scrum"
- set_fact: expose_basic_ui=true
    
- include: environment-setup.yml
- include: jaeger-setup.yml

- name: Create the external database service 
  shell: "oc process -n {{ project }} -f {{ workdir }}/database-service.yml -p DB_HOST={{ database }} | oc create -f -"
  when: "{{ external_db }}"
  tags:
    - db
    - postgresql

- name: Allows jenkins to access the production environment
  shell: "oc policy add-role-to-user edit system:serviceaccount:cicd:jenkins -n prod"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
    - jenkins   
