---
- name: Create a new Openshift project
  shell: "oc new-project {{ project }} --display-name='{{ project_description }}'"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift
        
- name: Define Openshift project
  shell: "oc project {{ project }}"
  tags:
    - openshift  

   

