---
- name: Verify if variables are set
  fail:
    msg: "[Target directory] and/or [OpenShift host] is not defined. Please edit vars.yml"
  when: (workdir is undefined) or (openshift is undefined) or (product is undefined)

- name: Login in OpenShift as {{ username }}
  shell: "oc login --insecure-skip-tls-verify=true -u {{ username }} -p {{ password }} {{ openshift }}"
  tags:
    - openshift

- name: Adjust SCC
  shell: "oc patch scc restricted -p '{\"runAsUser\":{\"type\":\"RunAsAny\"}}'"
  when: adjust_scc

- name: Create Workdir
  file:
    path: "{{ workdir }}"
    state: directory

- name: Checkout the boost console dependencies from github
  git:
    repo: "https://github.com/{{ github }}/estafet-openshift-boost.git"
    dest: "{{ workdir }}/estafet-openshift-boost"
    update: yes
  tags:
    - git      
    
- set_fact: roles="{{ workdir }}/estafet-openshift-boost/setup-environments/roles"
- set_fact: vars="{{ workdir }}/estafet-openshift-boost/setup-environments/roles"  
