---
# Define the name and description of the OpenShift project
- set_fact: project="monitoring"
- set_fact: project_description="Monitoring - Microservices Scrum"
    
- include: namespace-setup.yml
- include: imagestream-setup.yml

- name: Deploy the microservice for the console-application-api
  shell: 'oc new-app redhat-openjdk18-openshift:1.2~https://github.com/Estafet-LTD/estafet-openshift-boost-console-api-app.git --name=console-application-api -e OPENSHIFT_HOST_PORT={{ openshift }} -e OPENSHIFT_USER={{ username }} -e OPENSHIFT_PASSWORD={{ password }} -e PRODUCT_LABEL=microservices-scrum'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift         
    
- name: Wait for the microservice to become available console-application-api
  shell : "oc rollout status dc/console-application-api"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift    

- name: Deploy the microservice for the console-prod-api
  shell: 'oc new-app redhat-openjdk18-openshift:1.2~https://github.com/Estafet-LTD/estafet-openshift-boost-console-api-prod.git --name=console-prod-api -e OPENSHIFT_HOST_PORT={{ openshift }} -e OPENSHIFT_USER={{ username }} -e OPENSHIFT_PASSWORD={{ password }} -e PRODUCT_LABEL=microservices-scrum'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift         
    
- name: Wait for the microservice to become available console-prod-api
  shell : "oc rollout status dc/console-prod-api"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift    
    