---
# Define the name and description of the OpenShift project
- set_fact: project="monitoring"
- set_fact: project_description="Monitoring - Microservices Scrum"
    
- include: namespace-setup.yml
- include: imagestream-setup.yml
- include: jaeger-setup.yml
- include: pgadmin-setup.yml

- set_fact: service_envs="-e JAEGER_SAMPLER_TYPE=const -e JAEGER_SAMPLER_PARAM=1 -e JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger-agent.{{ project }}.svc:5778 -e JAEGER_AGENT_HOST=jaeger-agent.{{ project }}.svc"

- name: Deploy the microservice for the console-application-api
  shell: 'oc new-app redhat-openjdk18-openshift:1.2~https://github.com/Estafet-LTD/estafet-openshift-boost-console-api-app.git --name=console-application-api -e OPENSHIFT_HOST_PORT={{ openshift }} -e OPENSHIFT_USER={{ username }} -e OPENSHIFT_PASSWORD={{ password }} -e PRODUCT_LABEL=microservices-scrum {{ service_envs }}'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift         
    
- name: Wait for the microservice to become available console-application-api
  shell : "oc rollout status dc/console-application-api"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift    

- name: Deploy the microservice for the console-prod-api
  shell: 'oc new-app redhat-openjdk18-openshift:1.2~https://github.com/Estafet-LTD/estafet-openshift-boost-console-api-prod.git --name=console-prod-api -e OPENSHIFT_HOST_PORT={{ openshift }} -e OPENSHIFT_USER={{ username }} -e OPENSHIFT_PASSWORD={{ password }} -e PRODUCT_LABEL=microservices-scrum {{ service_envs }}'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift         
    
- name: Wait for the microservice to become available console-prod-api
  shell : "oc rollout status dc/console-prod-api"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift    

- name: Deploy the microservice for the console-test-api
  shell: 'oc new-app redhat-openjdk18-openshift:1.2~https://github.com/Estafet-LTD/estafet-openshift-boost-console-api-test.git --name=console-test-api -e OPENSHIFT_HOST_PORT={{ openshift }} -e OPENSHIFT_USER={{ username }} -e OPENSHIFT_PASSWORD={{ password }} -e PRODUCT_LABEL=microservices-scrum {{ service_envs }}'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift         
    
- name: Wait for the microservice to become available console-test-api
  shell : "oc rollout status dc/console-test-api"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift    
    
- name: Deploy the microservice for the console-build-api
  shell: 'oc new-app redhat-openjdk18-openshift:1.2~https://github.com/Estafet-LTD/estafet-openshift-boost-console-api-build.git --name=console-build-api -e OPENSHIFT_HOST_PORT={{ openshift }} -e OPENSHIFT_USER={{ username }} -e OPENSHIFT_PASSWORD={{ password }} -e PRODUCT_LABEL=microservices-scrum {{ service_envs }}'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift         
    
- name: Wait for the microservice to become available console-build-api
  shell : "oc rollout status dc/console-build-api"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift    

- name: Deploy the microservice for the console-ui
  shell: 'oc new-app redhat-openjdk18-openshift:1.2~https://github.com/Estafet-LTD/estafet-openshift-boost-console-ui.git --name=console-ui {{ service_envs }}'
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift         
    
- name: Wait for the microservice to become available console-ui
  shell : "oc rollout status dc/console-build-api"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift    
    