---
# Define the name and description of the OpenShift project
- set_fact: project="prod"
- set_fact: project_description="Production - Microservices Scrum"

- include: namespace-setup.yml
- include: jaeger-setup.yml
- include: imagestream-setup.yml
- include: external-db.yml
- include: add-jenkins-role.yml

- name: Create a route to expose the application
  shell: "oc process -n {{ project }} -f {{ inventory_dir }}/templates/basic-ui-prod-route.yml | oc apply -f -"
  register: command_result
  failed_when: "'exists' not in command_result.stderr and command_result.rc != 0"
  changed_when: "'exists' not in command_result.stderr"
  tags:
    - openshift  
