---
# the Absolute path where you want to checkout the sourcecode
workdir: "{{ ansible_env.HOME }}/.estafet"

# Does the use an external db
external_db: false

# Uncomment the following line to adjust the SCC (not using CDK3/minishift)
adjust_scc: false

# Define the name of the OpenShift project
project: microservices-scrum

# Define whether this is a local or cloud environment
cloud_environment: false

# Project Description
project_description: "Development Environment for Microservices Scrum"

# specify whether to remove the readiness probe for amq - this is a workaround for an issue with oc cluster up on windows
remove_amq_readiness: true

# enable readiness probe
readiness_probe: false

# amq url used for local environments
amq_url: tcp://broker-amq-tcp.microservices-scrum.svc:61616

# test environment flag
test_environment: false