---
# Define the name and description of the OpenShift project
- set_fact: project_name="prod"
- set_fact: project_description="Production/Demo Environment for Microservices Scrum"
    
- include: environment-setup.yml
- include: jaeger-setup.yml
