---
- name: Install Estafet Microservices Application in Openshift
  hosts: localhost
  vars_files:
    - vars.yml
    - create-environments-vars.yml    
  tasks:  
    - include: initial-setup.yml
    - include: create-dev-environment.yml
    - include: create-test-environment.yml
    - include: create-prod-environment.yml
    - include: create-cicd-environment.yml
