---
- name: Install Estafet Microservices Application in Openshift
  hosts: localhost
  vars_files:
    - microservices-scrum-vars.yml
    - vars.yml    
  tasks:  
    - include: initial-setup.yml
    - include: environment-setup.yml
    - include: jaeger-setup.yml
    - include: microservices-setup.yml
