apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: basic-ui-prod-route
parameters:
- description: Defines that hostname of the for the database service
  name: ENV
  value: green 
  required: true
objects:
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: basic-ui
    name: basic-ui
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${ENV}basic-ui
      weight: 100
    wildcardPolicy: None