apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: setup-pipelines
parameters:
- description: Defines the location of the estafet github (change this if you have forked and want to use another github)
  name: GITHUB
  required: true
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: setup-pipeline
    name: setup-pipeline
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/${GITHUB}/estafet-microservices-scrum"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: setup-environments/pipelines/setup-pipeline.groovy
      type: JenkinsPipeline
  status:
    lastVersion: 0