---
- name: Recreate the prod environment
  hosts: localhost
  vars_files:
    - create-prod-environment-vars.yml
    - microservices-vars.yml 
  tasks:  
    - include: initial-setup.yml
    - include: create-prod-environment.yml
