---
# the Absolute path where you want to checkout the sourcecode
workdir: "{{ ansible_env.HOME }}/.estafet"

# UNCOMENT Define the OpenShift host:port address
openshift: 10.0.75.2:8443

# Your OpenShift credentials
username: developer
password: developer

# Uncomment the following line to adjust the SCC (not using CDK3/minishift)
adjust_scc: false

# defines the location of the estafet github (change this if you have forked and want to use another github)
github: https://github.com/Estafet-LTD

# specify whether to remove the readiness probe for amq - this is a workaround for an issue with oc cluster up on windows
remove_amq_readiness: true

# enable readiness probe
readiness_probe: true

# amq url used for the dev environment
amq_url: tcp://localhost:61616

# test environment flag
test_environment: false