---
# the Absolute path where you want to checkout the sourcecode
workdir: "{{ ansible_env.HOME }}/.estafet"

# Your OpenShift credentials
username: admin
password: 123

# Is the openshift cluster local or cloud 
cloud_openshift: true

# Does the use an external db
external_db: true

# Uncomment the following line to adjust the SCC (not using CDK3/minishift)
adjust_scc: false

# defines the location of the estafet github (change this if you have forked and want to use another github)
github: https://github.com/Estafet-LTD

# specify whether to remove the readiness probe for amq - this is a workaround for an issue with oc cluster up on windows
remove_amq_readiness: true

# enable readiness probe
readiness_probe: true

# amq url used for the dev environment
amq_url: tcp://localhost:61616

# test environment flag
test_environment: false

microservices_scrum_environments:
  - name: dev
  - name: test
  - name: prod        
