---
- name: Create the databases for the RDS psotgres instance
  hosts: all
  vars_files:
    - microservices-vars.yml

- postgresql_db:
    db: "dev-{{ item.name }}"
    login_host: "{{ database }}"
    login_password: welcome1
    state: present
  with_items: "{{ microservices_scrum_projects }}"
  when: "{{ item.db }}"  
  tags:
    - db
    - postgresql

- postgresql_db:
    db: "test-{{ item.name }}"
    login_host: "{{ database }}"
    login_password: welcome1
    state: present
  with_items: "{{ microservices_scrum_projects }}"
  when: "{{ item.db }}"  
  tags:
    - db
    - postgresql

- postgresql_db:
    db: "prod-{{ item.name }}"
    login_host: "{{ database }}"
    login_password: welcome1
    state: present
  with_items: "{{ microservices_scrum_projects }}"
  when: "{{ item.db }}"  
  tags:
    - db
    - postgresql
