---
- name: Login in OpenShift as {{ username }}
  shell: "oc login --insecure-skip-tls-verify=true -u {{ username }} -p {{ password }} {{ openshift }}"
  tags:
    - openshift
        
- name: Define Openshift project
  shell: "oc project {{ project }}"
  tags:
    - openshift  

- include: amq-vars.yml
- include: create-db.yml

- name: Create the microservices applications using the source to image builder
  include_tasks: "{{ workdir }}/{{ item.repo }}/ansible/create-app-tasks.yml repo={{ item.repo }} broker_pod_user={{ broker_pod_user }} broker_pod_password={{ broker_pod_password }}"
  with_items: "{{ microservices_scrum_projects }}"
  tags:
    - openshift   
  

    