---
# Environments definition - add new environments here
environments:

  repo: estafet-microservices-scrum
  jaeger: true
  db: postgres
  amq: true

  stages:
  - name: build
    display: Build
    description: Build Environment 
    wiremock: true 
    role: edit
    next: test
    
  - name: test
    display: Test
    description: Test Environment
    test_repo: estafet-microservices-scrum-qa
    wiremock: false   
    role: edit
    next: perf
    
  - name: perf
    display: Performance
    description: Performance Test Environment
    test_repo: estafet-microservices-scrum-qa-perf
    wiremock: false 
    role: view
    next: prod
    
  - name: prod
    display: Production
    description: Production Environment
    test_repo: estafet-microservices-scrum-qa-prod
    wiremock: false
    next: end    