---
# Uncomment the following line to adjust the SCC (not using CDK3/minishift)
adjust_scc: false

# Define the name of the OpenShift project
project: microservices-scrum

# Project Description
project_description: "Development Environment for Microservices Scrum"

# test environment flag
test_environment: false